import type { Analytics } from '../types/analytics';
const n = (value: number | null | undefined) => value == null ? 'Unavailable' : value.toLocaleString('en-IN', { maximumFractionDigits: 10 });
export default function ShowMath({ data: d }: { data: Analytics }) {
  const t = d.temporal, a = d.attention, p = d.personal, v = d.volatility;
  return <details className="math-drawer"><summary>Show the math <span>Exact inputs. Visible contributions.</span></summary>
    <p className="caption">Inputs below retain up to 10 decimal places; calculations use the unrounded backend values. Published scores are rounded to one decimal place.</p>
    <div className="math-grid">
      <article><h3>01 / Today</h3><p>Current ₹{n(d.observation.current_price)} · previous ₹{n(t.previous_session_close)}</p><code>(current / previous − 1) × 100</code><strong>{n(t.session_change_pct)}{t.session_change_pct === null ? '' : '%'}</strong></article>
      <article><h3>02 / Since I looked</h3><p>Current ₹{n(d.observation.current_price)} · saved price {t.last_viewed_price === null ? 'No baseline yet' : `₹${n(t.last_viewed_price)}`}</p><code>(current / last viewed − 1) × 100</code><strong>{t.since_last_view_pct === null ? 'No baseline yet' : `${n(t.since_last_view_pct)}%`}</strong></article>
      <article><h3>03 / Unusualness</h3><p>Session return {n(t.session_return)} · canonical volatility {n(v?.canonical_value)}</p><code>abs(session return) / canonical volatility</code><strong>{v ? `${n(v.unusualness_ratio)}×` : 'Unavailable'}</strong><p className="caption">{v ? `Raw volatility: ${n(v.raw_value)}. Effective floor: ${n(v.effective_floor)} (0.5%), ${v.floor_applied ? 'applied' : 'not applied'}. ${v.sample_count} returns, including the current session; fewer than two returns use the floor.` : 'Insufficient session history.'}</p></article>
      <article><h3>04 / Volume</h3><p>Current {n(d.volume.current_session_volume)} · baseline {n(d.volume.baseline_average_volume)} over {d.volume.baseline_sample_count} prior sessions</p><code>latest cumulative volume / baseline average</code><strong>{d.volume.volume_ratio === null ? 'Unavailable' : `${n(d.volume.volume_ratio)}×`}</strong><p className="caption">Previous session volumes use each session’s latest observation. The canonical engine uses 1× if its baseline average is zero.</p></article>
      <article><h3>05 / Objective significance</h3>{a ? <><MathBar label="Return" value={a.return_contribution} max={45}/><MathBar label="Volume" value={a.volume_contribution} max={25}/><MathBar label="Technical" value={a.technical_contribution} max={10}/><code>return + volume + technical</code><strong>{n(a.objective_exact)} → {a.objective_score.toFixed(1)}</strong><p className="caption">Return: min(unusualness / 3, 1) × 45. Volume: min(max(ratio − 1, 0) / 1.5, 1) × 25. Technical: 10 if current close exceeds the previous {d.technical?.sample_count} sessions’ maximum close of ₹{n(d.technical?.previous_window_max_close)}.</p></> : <p>Unavailable</p>}</article>
      <article><h3>06 / Personal relevance</h3>{p ? <><MathBar label="Since view" value={p.since_view_contribution} max={20}/><MathBar label="Profile" value={p.profile_contribution} max={15}/><code>since-view points + profile points</code><strong>{n(p.personal_exact)} → {p.preference_fit.toFixed(1)}</strong><p className="caption">Since view: min(abs(return) / 0.05, 1) × 20; no baseline contributes 0. Profile: up to three matching dimensions, 5 points each.</p>{p.profile_reasons.map((r,i) => <p className="caption" key={i}>{r.message}</p>)}</> : <p>Unavailable</p>}</article>
    </div>
    <div className="math-final"><p className="eyebrow">Final attention / capped at 100</p><code>min(objective + personal relevance, 100)</code><strong>{a && p && d.final ? `min(${n(a.objective_exact)} + ${n(p.personal_exact)}, 100) → ${d.final.attention_score.toFixed(1)}` : 'Unavailable'}</strong></div>
  </details>;
}
function MathBar({label,value,max}:{label:string;value:number;max:number}) { return <div className="math-bar"><span>{label}</span><meter aria-label={`${label} contribution`} min={0} max={max} value={value}/><span>{n(value)}</span></div>; }
