"""add onboarding_completed to user_profiles

Revision ID: 13cb93b9ddc5
Revises: b2f14a9c7d3e
Create Date: 2026-09-05 00:16:12.061053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13cb93b9ddc5'
down_revision: Union[str, None] = 'b2f14a9c7d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.drop_column('user_profiles', 'onboarding_completed')
    # ### end Alembic commands ###
